/local_costmap/local_costmap:
  ros__parameters:
    /bond_disable_heartbeat_timeout: true
    always_send_full_costmap: true
    autostart_node: false
    bond_heartbeat_period: 0.1
    filters: []
    footprint: '[[0.4,0.36],[0.4,-0.36],[-0.4,-0.36],[-0.4,0.36]]'
    footprint_padding: 0.009999999776482582
    global_frame: odom
    height: 5
    inflation_layer:
      cost_scaling_factor: 3.0
      enabled: true
      inflate_around_unknown: false
      inflate_unknown: false
      inflation_radius: 0.55
      plugin: nav2_costmap_2d::InflationLayer
    initial_transform_timeout: 60.0
    lethal_cost_threshold: 100
    map_topic: /map
    map_vis_z: 0.0
    observation_sources: ''
    obstacle_layer:
      combination_method: 1
      enabled: true
      footprint_clearing_enabled: true
      max_obstacle_height: 2.0
      min_obstacle_height: 0.0
      observation_sources: scan
      plugin: nav2_costmap_2d::ObstacleLayer
      scan:
        clearing: true
        data_type: LaserScan
        expected_update_rate: 0.0
        inf_is_valid: true
        marking: true
        max_obstacle_height: 2.0
        min_obstacle_height: 0.0
        observation_persistence: 0.0
        obstacle_max_range: 9.0
        obstacle_min_range: 0.0
        raytrace_max_range: 10.0
        raytrace_min_range: 0.0
        sensor_frame: ''
        topic: /scan
    origin_x: 0.0
    origin_y: 0.0
    plugins:
    - obstacle_layer
    - inflation_layer
    publish_frequency: 4.0
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
    resolution: 0.05
    robot_base_frame: base_footprint
    robot_radius: 0.1
    rolling_window: true
    start_type_description_service: true
    track_unknown_space: false
    transform_tolerance: 0.3
    trinary_costmap: true
    unknown_cost_value: 255
    update_frequency: 8.0
    use_maximum: false
    use_sim_time: true
    width: 5

