joint_limits:
  shoulder_pan_joint: {has_velocity_limits: true, max_velocity: 1.00, has_acceleration_limits: true, max_acceleration: 1.50}
  shoulder_lift_joint: {has_velocity_limits: true, max_velocity: 1.00, has_acceleration_limits: true, max_acceleration: 1.50}
  elbow_joint: {has_velocity_limits: true, max_velocity: 1.00, has_acceleration_limits: true, max_acceleration: 1.50}
  wrist_1_joint: {has_velocity_limits: true, max_velocity: 1.20, has_acceleration_limits: true, max_acceleration: 1.80}
  wrist_2_joint: {has_velocity_limits: true, max_velocity: 1.20, has_acceleration_limits: true, max_acceleration: 1.80}
  wrist_3_joint: {has_velocity_limits: true, max_velocity: 1.20, has_acceleration_limits: true, max_acceleration: 1.80}
  robotiq_85_left_knuckle_joint: {has_velocity_limits: true, max_velocity: 0.50, has_acceleration_limits: true, max_acceleration: 1.00}
