planning_plugin: ompl_interface/OMPLPlanner
request_adapters: >-
  default_planning_request_adapters/ResolveConstraintFrames
  default_planning_request_adapters/ValidateWorkspaceBounds
  default_planning_request_adapters/CheckStartStateBounds
  default_planning_request_adapters/CheckStartStateCollision
response_adapters: >-
  default_planning_response_adapters/AddTimeOptimalParameterization
  default_planning_response_adapters/ValidateSolution
manipulator:
  planner_configs: [RRTConnectkConfigDefault]
  longest_valid_segment_fraction: 0.01
