controller_manager:
  ros__parameters:
    update_rate: 250
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    base_controller:
      type: diff_drive_controller/DiffDriveController
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    cleaning_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    storage_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    brush_controller:
      type: velocity_controllers/JointGroupVelocityController

base_controller:
  ros__parameters:
    left_wheel_names: [front_left_wheel_joint, rear_left_wheel_joint]
    right_wheel_names: [front_right_wheel_joint, rear_right_wheel_joint]
    wheel_separation: 0.584
    wheel_radius: 0.186
    wheels_per_side: 2
    publish_rate: 50.0
    position_feedback: true
    open_loop: false
    cmd_vel_timeout: 0.5
    use_stamped_vel: false

arm_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      - robotiq_85_left_knuckle_joint
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_partial_joints_goal: true

cleaning_controller:
  ros__parameters:
    joints:
      - cleaning_lift_joint
      - squeegee_pitch_joint
      - squeegee_float_joint
    command_interfaces: [position]
    state_interfaces: [position, velocity]

storage_controller:
  ros__parameters:
    joints: [dry_bin_lid_joint, wastewater_lid_joint]
    command_interfaces: [position]
    state_interfaces: [position, velocity]

brush_controller:
  ros__parameters:
    joints: [left_side_brush_joint, right_side_brush_joint, central_roller_joint]
    interface_name: velocity
