/amcl:
  ros__parameters:
    /bond_disable_heartbeat_timeout: true
    alpha1: 0.001
    alpha2: 0.001
    alpha3: 0.002
    alpha4: 0.002
    alpha5: 0.001
    always_reset_initial_pose: false
    autostart_node: false
    base_frame_id: base_link
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    bond_heartbeat_period: 0.1
    do_beamskip: false
    first_map_only: false
    freespace_downsampling: false
    global_frame_id: map
    initial_pose:
      x: 0.0
      y: 0.0
      yaw: 0.0
      z: 0.0
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: likelihood_field_prob
    map_topic: map
    max_beams: 180
    max_particles: 8000
    min_particles: 2000
    odom_frame_id: odom
    pf_err: 0.02
    pf_z: 0.99
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
        subscription:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf_static:
        subscription:
          depth: 100
          history: keep_last
          reliability: reliable
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: nav2_amcl::DifferentialMotionModel
    save_pose_rate: 0.5
    scan_topic: /scan/navigation
    set_initial_pose: true
    sigma_hit: 0.2
    start_type_description_service: true
    tf_broadcast: false
    transform_tolerance: 0.5
    update_min_a: 0.02
    update_min_d: 0.02
    use_sim_time: true
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05

