#!/usr/bin/env python3
"""Create compact Stage4W review evidence without copying raw MCAP payloads."""

import argparse
import hashlib
import json
import shutil
from pathlib import Path


def load(path):
    return json.loads(path.read_text(encoding="utf-8"))


def copy(source, destination):
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--localization", type=Path, required=True)
    parser.add_argument("--static", type=Path, required=True)
    parser.add_argument("--dynamic", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)

    localization_path = args.localization / "stage4v_localization_report.json"
    static_path = args.static / "stage4w_static_matrix_report.json"
    dynamic_path = args.dynamic / "stage4w_dynamic_report.json"
    localization = load(localization_path)
    static = load(static_path)
    dynamic = load(dynamic_path)

    component_totals = sorted({
        int(trial["component_terminal_total"]) for trial in static["trials"]
    })
    all_generated_components_succeeded = all(
        int(trial["component_terminal_success_count"])
        == int(trial["component_terminal_total"])
        for trial in static["trials"]
    )
    gates = {
        "hybrid_localization_regression_10_of_10": bool(
            localization.get("formal_gate_pass")
            and localization.get("completed_seed_count") == 10
        ),
        "ground_truth_control_violations_zero": int(
            localization.get("ground_truth_control_violation_count", -1)
        ) == 0,
        "static_coverage_5_of_5": bool(static.get("success")),
        "transit_success_5_of_5": all(
            bool(trial.get("transit_success")) for trial in static["trials"]
        ),
        "all_generated_components_succeeded": all_generated_components_succeeded,
        "empirical_coverage_at_least_90pct": all(
            float(trial.get("empirical_coverage_rate") or 0.0) >= 0.90
            for trial in static["trials"]
        ),
        "collision_zero": (
            all(int(trial.get("collision_count", -1)) == 0 for trial in static["trials"])
            and bool(dynamic.get("gates", {}).get("collision_count_zero"))
        ),
        "keepout_violation_zero": (
            all(
                int(trial.get("keepout_violation_sample_count", -1)) == 0
                for trial in static["trials"]
            )
            and bool(dynamic.get("gates", {}).get("coverage_keepout_violations_zero"))
            and bool(dynamic.get("gates", {}).get("keepout_violations_zero"))
        ),
        "brush_only_on_swaths_and_final_false": (
            all(
                int(trial.get("brush_state_violation_sample_count", -1)) == 0
                and bool(trial.get("brush_disabled_on_exit"))
                for trial in static["trials"]
            )
            and bool(dynamic.get("gates", {}).get("brush_only_during_swaths"))
            and bool(dynamic.get("gates", {}).get("brush_final_state_false"))
        ),
        "dynamic_valid_trials_at_least_20": bool(
            dynamic.get("gates", {}).get(
                "dynamic_obstacle_valid_trials_at_least_20"
            )
        ),
        "estop_p95_at_most_1s": bool(
            dynamic.get("gates", {}).get("emergency_stop_p95_at_most_1s")
        ),
        "complete_rosbag_replay": (
            all(bool(trial.get("rosbag_replay")) for trial in static["trials"])
            and bool(dynamic.get("gates", {}).get("complete_rosbag_replay"))
        ),
    }
    ready = all(gates.values())
    summary = {
        "schema_version": 1,
        "stage": "Stage4W",
        "gates": gates,
        "ready_for_gpt_review_stage4w": ready,
        "ready_for_stage5a": ready,
        "component_count_semantics": {
            "formal_generated_component_totals": component_totals,
            "historical_stage4v_literal_23_component_check": "not_applicable",
            "reason": (
                "Stage4V's 23 components came from no headland and no inner cutouts; "
                "Stage4W executes every component generated by the unified cleanable geometry."
            ),
        },
        "localization_rmse_m": localization.get("rmse_m"),
        "static_trials": static.get("trials"),
        "dynamic_valid_trial_count": dynamic.get("dynamic_obstacles", {}).get(
            "dynamic_obstacle_valid_trials"
        ),
        "estop_latency_sec": dynamic.get("emergency_stop", {}).get("latency_sec"),
        "efficiency": dynamic.get("efficiency"),
        "competition_efficiency_pass": False,
        "scope_boundary": (
            "Stop after GPT review packaging; no perception training, J6 toolchain, "
            "or physical deployment was started."
        ),
    }
    summary_path = args.output / "stage4w_summary.json"
    summary_path.write_text(
        json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    copy(localization_path, args.output / "stage4w_localization_report.json")
    copy(static_path, args.output / "stage4w_static_matrix_report.json")
    copy(dynamic_path, args.output / "stage4w_dynamic_report.json")
    for trial_dir in sorted(args.static.glob("seed_*")):
        source = trial_dir / "stage4w_static_summary.json"
        if source.is_file():
            copy(source, args.output / "static_trials" / trial_dir.name / source.name)
        bag_info = trial_dir / "rosbag_info.txt"
        if bag_info.is_file():
            copy(bag_info, args.output / "static_trials" / trial_dir.name / bag_info.name)
    dynamic_bag_info = args.dynamic / "rosbag_info.txt"
    if dynamic_bag_info.is_file():
        copy(dynamic_bag_info, args.output / "dynamic_rosbag_info.txt")

    files = sorted(
        path for path in args.output.rglob("*")
        if path.is_file() and path.name != "MANIFEST.json"
    )
    manifest = {
        "schema_version": 1,
        "file_count": len(files),
        "files": [
            {
                "path": path.relative_to(args.output).as_posix(),
                "bytes": path.stat().st_size,
                "sha256": sha256(path),
            }
            for path in files
        ],
    }
    (args.output / "MANIFEST.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(summary, ensure_ascii=False))
    return 0 if ready else 2


if __name__ == "__main__":
    raise SystemExit(main())
