"""Unit coverage for HBM evidence producers.

Fixtures deliberately use tiny synthetic files and a mocked compiler.  They
exercise receipt semantics only and never stand in for a real HBM claim.
"""

from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

SCRIPTS = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS))

import execute_dosod_hbm_compile as compile_producer
import run_dosod_hbm_x86_parity as parity
import validate_dosod_quantized_metric_regression as metric_regression


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _write_json(path: Path, value: object) -> None:
    path.write_text(json.dumps(value), encoding="utf-8")


class CompileProducerTests(unittest.TestCase):
    def _inputs(self, root: Path) -> tuple[Path, Path, Path, Path, Path]:
        try:
            import yaml
        except ImportError as exc:  # this is also a production precondition
            self.skipTest(f"PyYAML unavailable: {exc}")
        compiler = root / "fake-hb-compile"
        compiler.write_bytes(b"unit-test compiler")
        contract = root / "contract.json"
        preflight = root / "preflight.json"
        identity = root / "identity.json"
        working = root / "working"
        config = root / "config.yaml"
        _write_json(contract, {"toolchain": {"oe_version": "3.7.0", "required_versions": {"hbdk4_compiler": "4.7.5", "hmct": "2.6.5", "horizon_tc_ui": "3.5.3"}},
                               "compile_recipe": {"march": "nash-m"}, "output": {"relative_path": "dosod/dosod_mlp3x_s_tzcup_rep-int16.hbm"}, "model": {"sha256": "a" * 64}})
        _write_json(preflight, {"preflight_pass": True, "compile_config_emitted": True, "compile_executed": False,
                                "hbm_status": "HBM_NOT_PRODUCED", "calibration": {"manifest_sha256": "b" * 64}})
        _write_json(identity, {"identity_verified": True, "oe_version": "3.7.0", "required_versions": {"hbdk4_compiler": "4.7.5", "hmct": "2.6.5", "horizon_tc_ui": "3.5.3"},
                               "hb_compile_executable_sha256": _sha(compiler)})
        config.write_text(yaml.safe_dump({"model_parameters": {"march": "nash-m", "output_model_file_prefix": "dosod_mlp3x_s_tzcup_rep-int16", "working_dir": str(working)}}), encoding="utf-8")
        return contract, preflight, config, identity, compiler

    def test_success_requires_real_returncode_and_nonempty_output(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            contract, preflight, config, identity, compiler = self._inputs(root)

            def runner(command, **_kwargs):
                output = root / "working" / "dosod_mlp3x_s_tzcup_rep-int16.hbm"
                output.parent.mkdir(parents=True, exist_ok=True)
                output.write_bytes(b"fixture HBM generated by mocked runner")
                return subprocess.CompletedProcess(command, 0, "compiled", "")

            with mock.patch.object(compile_producer.shutil, "which", return_value=str(compiler)):
                receipt = compile_producer.execute_compile(contract_path=contract, preflight_path=preflight, config_path=config,
                                                           identity_path=identity, output=root / "evidence", compiler="fake-hb_compile", runner=runner)
            self.assertEqual(receipt["status"], "COMPILED_NOT_BOARD_ACCEPTED")
            self.assertEqual(receipt["returncode"], 0)
            self.assertTrue((root / "evidence" / "dosod_hbm_compile_receipt.json").is_file())

    def test_nonzero_compiler_cannot_pass_even_if_no_exception(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            contract, preflight, config, identity, compiler = self._inputs(root)
            with mock.patch.object(compile_producer.shutil, "which", return_value=str(compiler)):
                receipt = compile_producer.execute_compile(
                    contract_path=contract, preflight_path=preflight, config_path=config, identity_path=identity,
                    output=root / "evidence", compiler="fake-hb_compile",
                    runner=lambda command, **_kwargs: subprocess.CompletedProcess(command, 7, "", "compiler failed"),
                )
            self.assertEqual(receipt["status"], "BLOCKED")
            self.assertIn("hb_compile_nonzero_returncode", receipt["blockers"])


class MetricRegressionTests(unittest.TestCase):
    def _metrics(self, *, backend: str, hbm_sha: str | None, source: str) -> dict:
        execution = {"backend": backend, "command": [backend, "evaluate"], "returncode": 0}
        if hbm_sha:
            execution["hbm_sha256"] = hbm_sha
        return {"report_id": metric_regression.METRICS_REPORT_ID, "status": "VERIFIED", "execution": execution,
                "dataset": {"status": "FROZEN", "dataset_id": "real-holdout-fixture", "source_sha256": [source]},
                "class_order": metric_regression.CLASS_ORDER,
                "metrics": {"macro_f1": 0.9, "negative_fp_per_frame": 0.01,
                            "classes": {name: {"f1": 0.9} for name in metric_regression.CLASS_ORDER}}}

    def test_pass_requires_same_non_calibration_holdout_and_thresholds(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            hbm = root / "model.hbm"; hbm.write_bytes(b"unit-test hbm")
            hbm_sha = _sha(hbm)
            calibration = root / "calibration.json"; _write_json(calibration, {"status": "FROZEN", "records": [{"source_sha256": "a" * 64}]})
            compile_receipt = root / "compile.json"; _write_json(compile_receipt, {"status": "COMPILED_NOT_BOARD_ACCEPTED", "returncode": 0, "output_sha256": hbm_sha, "output_byte_size": hbm.stat().st_size})
            reference = root / "reference.json"; _write_json(reference, self._metrics(backend="onnx", hbm_sha=None, source="b" * 64))
            quantized = root / "quantized.json"; _write_json(quantized, self._metrics(backend="hbm", hbm_sha=hbm_sha, source="b" * 64))
            thresholds = root / "thresholds.json"; _write_json(thresholds, {"schema_version": 1, "report_id": metric_regression.THRESHOLDS_REPORT_ID,
                                                                            "minimum": {"macro_f1": 0.8}, "maximum": {"negative_fp_per_frame": 0.05},
                                                                            "max_drop": {"classes.litter_cube.f1": 0.02}})
            result = metric_regression.validate_regression(hbm=hbm, compile_receipt_path=compile_receipt,
                                                            calibration_manifest=calibration, reference_report_path=reference,
                                                            quantized_report_path=quantized, thresholds_path=thresholds, output=root / "evidence")
            self.assertEqual(result["status"], "REGRESSION_PASSED")

    def test_calibration_overlap_is_blocked(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            hbm = root / "model.hbm"; hbm.write_bytes(b"unit-test hbm")
            hbm_sha = _sha(hbm)
            calibration = root / "calibration.json"; _write_json(calibration, {"status": "FROZEN", "records": [{"source_sha256": "a" * 64}]})
            compile_receipt = root / "compile.json"; _write_json(compile_receipt, {"status": "COMPILED_NOT_BOARD_ACCEPTED", "returncode": 0, "output_sha256": hbm_sha, "output_byte_size": hbm.stat().st_size})
            reference = root / "reference.json"; _write_json(reference, self._metrics(backend="onnx", hbm_sha=None, source="a" * 64))
            quantized = root / "quantized.json"; _write_json(quantized, self._metrics(backend="hbm", hbm_sha=hbm_sha, source="a" * 64))
            thresholds = root / "thresholds.json"; _write_json(thresholds, {"schema_version": 1, "report_id": metric_regression.THRESHOLDS_REPORT_ID, "minimum": {"macro_f1": 0.8}})
            result = metric_regression.validate_regression(hbm=hbm, compile_receipt_path=compile_receipt,
                                                            calibration_manifest=calibration, reference_report_path=reference,
                                                            quantized_report_path=quantized, thresholds_path=thresholds, output=root / "evidence")
            self.assertEqual(result["status"], "BLOCKED")
            self.assertTrue(any("ValueError" in item for item in result["blockers"]))


class ParityManifestTests(unittest.TestCase):
    def test_calibration_source_cannot_be_reused_as_parity_holdout(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            manifest = root / "holdout.json"
            _write_json(manifest, {"schema_version": 1, "status": "FROZEN",
                                   "hbm_input_adapter": {"status": "VERIFIED", "command": ["official-adapter"]},
                                   "records": [{"sample_id": "one", "source_sha256": "a" * 64,
                                                "onnx_input_npy": "input.npy", "hbm_input_binary": "input.bin"}]})
            with self.assertRaisesRegex(ValueError, "holdout_calibration_source_overlap"):
                parity._holdout_records(manifest, {"a" * 64})


if __name__ == "__main__":
    unittest.main()
